{% set name = "anaconda-cloud-auth" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud_auth-{{ version }}.tar.gz
  sha256: 60e0f839718e3e20aaa92bfd8fe1b32059228124c4dc31a7e48675cda69ff1ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.8
    - keyring
    - pkce
    - python-dotenv
    - pydantic <2.0
    - pyjwt
    - requests
    - cryptography >=3.4.0

test:
  imports:
    - anaconda_cloud_auth
  commands:
    - python -c "from anaconda_cloud_auth import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: A client auth library for Anaconda.cloud APIs
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
