{% set name = "anaconda-cloud-auth" %}
{% set version = "0.7.2" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud_auth-{{ version }}.tar.gz
  sha256: bdb49cdb5a22b5d0c1d825cf2b0529005628fa987b5a1466283d80722590044a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }}
    - keyring
    - pkce
    - python-dotenv
    - pydantic
    - pyjwt
    - requests
    - cryptography >=3.4.0
    - semver <4
    - anaconda-cli-base >=0.4.0
  run_constrained:
    - conda >=23.9.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - anaconda_cloud_auth
  commands:
    - python -c "from anaconda_cloud_auth import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: A client auth library for Anaconda.cloud APIs
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
